name: Build

on:
  workflow_dispatch:
    inputs:
      publish_artifacts:
        description: 'Publish artifacts (Y|N)'
        required: true
        default: 'Y'
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  PROJECT_NAME: df-compress

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.13"

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 9
          submodules: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install distribution dependencies
        run: pip install --upgrade setuptools wheel build twine
        if: matrix.python-version == 3.13

      - name: Create a distribution package
        run: python -m build
        if: matrix.python-version == 3.13

      - name: Upload distribution package
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
        if: matrix.python-version == 3.13

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: |
      github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_artifacts == 'Y')
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Twine
        run: python -m pip install --upgrade twine

      - name: Confirm Twine Installation
        run: python -m twine --version

      - name: Download a distribution artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish distribution 📦 to PyPI
        shell: bash
        run: python -m twine upload -r pypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
